CREATE TABLE [dbo].[PreLoadStudentEnrollmentHistory]
(
[SchoolYear] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistrictCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistrictName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistrictStudentID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermEndDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Term] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseTitle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StaffID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GradeLevelWhenCourseTaken] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LetterGrade] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditsAttempted] [float] NULL,
[CreditsEarned] [float] NULL,
[StateCourseCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContentAreaCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContentAreaName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APIBCourseCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APIBCourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTECIPCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTECIPName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTEClusterID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTEClusterName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTEPathwayID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTEPathwayName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CTEAssessment] [int] NULL,
[hasCTEIndustryCertificateFlag] [int] NULL,
[CTEVocCompleterFlag] [int] NULL,
[CTEDirectTranscriptionAvailableFlag] [int] NULL,
[TechPrepCourseFlag] [int] NULL,
[TechPrepProgramAreaCompleterFlag] [int] NULL,
[FullCourseDesignationCode] [int] NULL,
[InternationalBaccalaureateFlag] [int] NULL,
[CollegeattheHighSchoolFlag] [int] NULL,
[HonorsFlag] [int] NULL,
[AdvancedPlacementFlag] [int] NULL,
[RunningStartFlag] [int] NULL,
[CollegeAcademicDistributionRequirementsFlag] [int] NULL,
[CambridgeProgramFlag] [int] NULL,
[OnlineFlag] [int] NULL,
[SubmitDate] [datetime] NULL,
[ExtractDate] [datetime] NULL
) ON [PRIMARY]
GO
